# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Test bird station

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-bird-station:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./bird_detection_station
      run: |
        python -m pip install --upgrade pip
        pip install black pytest mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      working-directory: ./bird_detection_station
      run: black 
    - name: Run static type checker mypy
      working-directory: ./bird_detection_station
      run: mypy .    
    - name: Test with pytest
      working-directory: ./bird_detection_station
      run: pytest

